apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-gcp-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: devops-gcp-gke
        image: gcr.io/devops-gcp-project/devopsgcp:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-gcp-prod
  namespace: default
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: gcp
  type: LoadBalancer
